// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLiAqVZn4CGCJRTmaiXZIHQGCeCma--f8',
    appId: '1:875956008201:web:30708d58bd34f059fb0fd8',
    messagingSenderId: '875956008201',
    projectId: 'ai-project-738a2',
    authDomain: 'ai-project-738a2.firebaseapp.com',
    storageBucket: 'ai-project-738a2.firebasestorage.app',
    measurementId: 'G-328YM7YVN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVJsuOx4vYPvJ_ovubbxGJSX0IrYwNKMA',
    appId: '1:875956008201:android:d204df412919462bfb0fd8',
    messagingSenderId: '875956008201',
    projectId: 'ai-project-738a2',
    storageBucket: 'ai-project-738a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaM8UFkbt6pjd7my7zarjqWnJnfRQcmIg',
    appId: '1:875956008201:ios:357bc8f09e173b3cfb0fd8',
    messagingSenderId: '875956008201',
    projectId: 'ai-project-738a2',
    storageBucket: 'ai-project-738a2.firebasestorage.app',
    iosBundleId: 'com.example.genkitEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaM8UFkbt6pjd7my7zarjqWnJnfRQcmIg',
    appId: '1:875956008201:ios:357bc8f09e173b3cfb0fd8',
    messagingSenderId: '875956008201',
    projectId: 'ai-project-738a2',
    storageBucket: 'ai-project-738a2.firebasestorage.app',
    iosBundleId: 'com.example.genkitEx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLiAqVZn4CGCJRTmaiXZIHQGCeCma--f8',
    appId: '1:875956008201:web:67a80e7ca9dbd5e6fb0fd8',
    messagingSenderId: '875956008201',
    projectId: 'ai-project-738a2',
    authDomain: 'ai-project-738a2.firebaseapp.com',
    storageBucket: 'ai-project-738a2.firebasestorage.app',
    measurementId: 'G-N0TYP6F1NP',
  );
}
