// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUVF1VqnugkGxizvknulunBEB3ZQd4GMI',
    appId: '1:813801044485:web:4199d8c0ee34b020bb7a6c',
    messagingSenderId: '813801044485',
    projectId: 'czb-noob',
    authDomain: 'czb-noob.firebaseapp.com',
    storageBucket: 'czb-noob.appspot.com',
    measurementId: 'G-0J51NLCWWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXT8YnTHUOGAs71m9TOV50nNK51KZMIgQ',
    appId: '1:813801044485:android:c7ed32328fccc7e8bb7a6c',
    messagingSenderId: '813801044485',
    projectId: 'czb-noob',
    storageBucket: 'czb-noob.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjvHk3i7B4UyUKQBhZH0KPkWzIohzIwM',
    appId: '1:813801044485:ios:c7d82db0c9511100bb7a6c',
    messagingSenderId: '813801044485',
    projectId: 'czb-noob',
    storageBucket: 'czb-noob.appspot.com',
    iosBundleId: 'com.example.noob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpjvHk3i7B4UyUKQBhZH0KPkWzIohzIwM',
    appId: '1:813801044485:ios:c7d82db0c9511100bb7a6c',
    messagingSenderId: '813801044485',
    projectId: 'czb-noob',
    storageBucket: 'czb-noob.appspot.com',
    iosBundleId: 'com.example.noob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUVF1VqnugkGxizvknulunBEB3ZQd4GMI',
    appId: '1:813801044485:web:77b1d81e7b35bd59bb7a6c',
    messagingSenderId: '813801044485',
    projectId: 'czb-noob',
    authDomain: 'czb-noob.firebaseapp.com',
    storageBucket: 'czb-noob.appspot.com',
    measurementId: 'G-38T5G8TRCF',
  );
}
